spring:
  application:
    name: srping-tutorial
  datasource:
    url: "jdbc:postgresql://localhost:5432/airportdb"
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
  context-path: /api
